// <auto-generated />
namespace TrainingPlan.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class seth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seth));
        
        string IMigrationMetadata.Id
        {
            get { return "201904100703108_seth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
